// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snbwvguwhoovnvcxfjaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuYnd2Z3V3aG9vdm52Y3hmamF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzU4MTIsImV4cCI6MjA2NDQ1MTgxMn0.-fa2BCt5_m2ki2JUNovoZWIvPJMrBMV_n3VJHRF_ouI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);